<?php

namespace AppBundle\Repository;

/**
 * CategorieDeServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieDeServicesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategoriesDeServices($slug=null)
    {
        if($slug != null){
            $data = $this->findOneBy(array('slug'=> $slug));
        }else {
            $data = $this->findAll();
        }
        return $data;
    }
}
