<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Prestataire;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommentaires( Prestataire $prestataire=null)
    {
        if ($prestataire != null) {
            $data = $this->findOneBy(array('cibleCommentaire' => $prestataire));
        } else {
            $data = $this->findAll();
        }
        return $data;
    }


}
