<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Prestataire;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommentairesByIdPrestataire( $prestataireId)
    {
        $qb = $this->createQueryBuilder('c');
        $this->addAllJoins($qb);
        $qb->where('c.cibleCommentaire = :cible');
        $qb->setParameter('cible', $prestataireId);

        $qb->orderBy('c.encodage','DESC');

        $query = $qb->getQuery();
        $result = $query->getResult();

        return $result;
    }

    public function addAllJoins($qb)
    {
        $qb->leftJoin('c.auteurCommentaire','a')->addSelect('a');
    }



}
