<?php

namespace AppBundle\Repository;

/**
 * InternauteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternauteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInternautes($id)
    {
        if($id != -1){
            $data = $this->findOneBy(array('id'=> $id));
        }else {
            $data = $this->findAll();
        }
        return $data;
    }

    public function findAllAbonner()
    {
        $qb = $this->createQueryBuilder('i');
        $qb->where('i.newsletter = 1' );

        $qb->select('i.email');
        $query = $qb->getQuery();
        $result = $query->getScalarResult();
        $emails = array_column($result,"email");
        return $emails;
    }
}
