<?php

namespace AppBundle\Repository;

/**
 * LocaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaliteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithCP()
    {
        $qb = $this->createQueryBuilder('l');
        $qb->leftJoin('l.codePostal','cp')->addSelect('cp');
        $query = $qb->getQuery();
        $result = $query->getResult();
        return $result;
    }


}
