<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CategorieDeServices;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PrestataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestataireRepository extends EntityRepository
{

    public function findAllWithEverything()
    {
        return $this->searchAll(null,'','');
    }

    public function findOneWithEverythingBySlug($slug)
    {
        $qb = $this->createQueryBuilder('p');
        $this->addAllJoins($qb);

        $qb->where('p.slug =:slug');
        $qb->setParameter('slug', $slug);

        $qb->orderBy('p.nom', 'ASC');

        $query = $this->returnQuery($qb);
        return $this->returnSingleResult($query);
    }

    public function findAllWithEverythingByCateg(CategorieDeServices $categ)
    {
        $qb = $this->createQueryBuilder('p');
        $this->addBasicJoins($qb);
        $qb->leftJoin('p.localite', 'l')->addSelect('l');

        $qb->join('p.categories', 'c', 'WITH', $qb->expr()->eq('c.id', $categ->getId()));
        $qb->orderBy('p.nom', 'ASC');

        $query = $this->returnQuery($qb);
        return $this->returnResult($query);

    }

    public function findNMostRecentBasic(int $n)
    {
        $qb = $this->createQueryBuilder('p');
        $this->addAllJoins($qb);

        $qb->orderBy('p.inscription', 'DESC');
        $qb->setMaxResults($n);
        $pag = new Paginator($qb);
        return $pag;

    }

    public function searchAll($categorie,$localite,$motcle)
    {
        $qb = $this->createQueryBuilder('p');
        $this->addBasicJoins($qb);


        if (!is_null($categorie)){
            $qb->join('p.categories','c','WITH',$qb->expr()->in('c.id',$categorie))->andWhere('c.valide = 1');
        }else{
            $qb->leftJoin('p.categories','c')->addSelect('c')->andWhere('c.valide = 1');
        }

        if (!empty($localite)){
            $qb->join('p.localite','l','WITH', $qb->expr()->eq('l.id',$localite));
        }else{
            $qb->leftJoin('p.localite','l')->addSelect('l');
        }

        if(!empty($motcle)){
            $mc = "%".$motcle."%";
            $qb->add('where', $qb->expr()->like('p.nom','?1'));
            $qb->setParameter(1,$mc);

        }

        $qb->orderBy('p.nom', 'ASC');
        $query = $this->returnQuery($qb);

        return $query;
    }

    //fonction pas très utile mais qui existe pour des raisons de lisibilité

    protected function returnQuery(QueryBuilder $qb)
    {
        $query = $qb->getQuery();
        return $query;
    }

    protected function returnResult(Query $query)
    {
        $result = $query->getResult();
        return $result;
    }

    protected function returnSingleResult(Query $query)
    {
        $result = $query->getSingleResult();
        return $result;
    }


    protected function addAllJoins(QueryBuilder $qb)
    {
        $this->addBasicJoins($qb);

        $qb->leftJoin('p.categories', 'c')->addSelect('c')->andWhere('c.valide = 1');
        $qb->leftJoin('p.localite', 'l')->addSelect('l');
    }

    //ajoute les joins moins ceux concerner par les recherche etc
    protected function addBasicJoins(QueryBuilder $qb)
    {
        $qb->leftJoin('p.stages', 's')->addSelect('s');
        $qb->leftJoin('p.promotions', 'pr')->addSelect('pr');
        $qb->leftJoin('p.photos', 'ph')->addSelect('ph')->andWhere('ph.active = 1');
        $qb->leftJoin('p.logo', 'logo')->addSelect('logo');
        $qb->leftJoin('p.internautesFavoris', 'fav')->addSelect('fav');
        $qb->andWhere('p.banni = 0');
    }


}