<?php

namespace AppBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($email)
    {
        $qb = $this->createQueryBuilder('u');

        $qb->where('u.email = :email');
        $qb->setParameter('email', $email);

        $query = $qb->getQuery();

        return $query->getOneOrNullResult();

    }
}
