<?php

namespace AppBundle\Repository;

/**
 * UtilisateurTemporaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurTemporaireRepository extends \Doctrine\ORM\EntityRepository
{
}
