<?php

namespace AppBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Utilisateur;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($email)
    {
        $qb = $this->createQueryBuilder('u');

        $qb->where('u.email = :email');
        $qb->setParameter('email', $email);

        $query = $qb->getQuery();

        return $query->getOneOrNullResult();

    }

    public function incrementeEssaisInfructueux($username){

        $qb = $this->createQueryBuilder('u');
        $qb->update('AppBundle:Utilisateur','u');
        $qb->set('u.nbEssaisInfructueux','u.nbEssaisInfructueux+1');
        $qb->where('u.email = :email');
        $qb->setParameter('email', $username);
        $query = $qb->getQuery();
        return $query->execute();
    }
}
