imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_3_layout.html.twig']


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
#        entity_managers:
#                    default:
#                        mappings:
#                            gedmo_translatable:
#                                type: annotation
#                                prefix: Gedmo\Translatable\Entity
#                                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
#                                alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
#                                is_bundle: false
#                            gedmo_translator:
#                                type: annotation
#                                prefix: Gedmo\Translator\Entity
#                                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
#                                alias: GedmoTranslator # (optional) it will default to the name set for the mapping
#                                is_bundle: false
#                            gedmo_loggable:
#                                type: annotation
#                                prefix: Gedmo\Loggable\Entity
#                                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
#                                alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
#                                is_bundle: false
#                            gedmo_tree:
#                                type: annotation
#                                prefix: Gedmo\Tree\Entity
#                                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
#                                alias: GedmoTree # (optional) it will default to the name set for the mapping
#                                is_bundle: false

stof_doctrine_extensions:
    default_locale: fr_BE
    orm:
        default:
          sluggable: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

#KNP Paginator
knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: 'lib/list/knpPagination_surcharge.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template

# app/config/config.yml
easy_admin:
    site_name: 'Bien Être Admin'
    formats:
      date: 'd/m/Y'
      time: 'H:i'
      datetime: 'd/m/Y H:i:s'
    design:
        brand_color: '#009f8b'
        color_scheme: 'light'
        assets:
            favicon: 'faviconadmin.png'
    entities:
        Utilisateur:
            class: AppBundle\Entity\Utilisateur
            help: "Ceci est un message d'aide globale"
            label: 'Utilisateurs'
            list:
                title: 'Utilisateurs récents'
                max_results: 30
                fields:
                    - id
                    - { property: 'email', label: 'E-mail', type: 'email'}
                    - { property: 'motDePasse', label: 'mot de passe'}
                    - { property: 'type', label: 'type'}
                    - { property: 'adresseNum', label: '# Rue'}
                    - { property: 'adresseRue', label: 'Rue'}
                    - { property: 'codePostal', label: 'CP', type: 'association'}
                    - { property: 'localite', label: 'Localite', type: 'association'}
                    - { property: 'inscription', label: "Date d'inscription", type: 'datetime'}
                    - { property: 'nbEssaisInfructueux', label: "nbre d'essais infructueux"}
                    - { property: 'banni', label: 'bannis'}
                    - { property: 'confInscription', label: 'confirmation', type: 'boolean'}
            show:
                help: "Ceci est un message d'aide spécifique"
                max_results: 20
            search:
        Internaute:
            class: AppBundle\Entity\Internaute
        Prestataire:
            class: AppBundle\Entity\Prestataire
            label: 'Prestataires'
            list:
                title: 'Prestataires récents'
                max_results: 30
                fields:
                    - id
                    - { property: 'nom', label: 'nom'}
                    - { property: 'slug', label: 'slug'}
                    - { property: 'email', label: 'E-mail', type: 'email'}
                    - { property: 'motDePasse', label: 'mot de passe'}
                    - { property: 'siteInternet', label: 'site', type: 'url'}
                    - { property: 'emailContact', label: 'E-mail Contact', type: 'email'}
                    - { property: 'telephone', label: 'telephone', type: 'tel'}
                    - { property: 'numTVA', label: '# TVA'}
                    - { property: 'adresseNum', label: '# Rue'}
                    - { property: 'adresseRue', label: 'Rue'}
                    - { property: 'codePostal', label: 'CP', type: 'association'}
                    - { property: 'localite', label: 'Localite', type: 'association'}
                    - { property: 'inscription', label: "Date d'inscription", type: 'datetime'}
                    - { property: 'nbEssaisInfructueux', label: "nbre d'essais infructueux"}
                    - { property: 'banni', label: 'bannis'}
                    - { property: 'confInscription', label: 'confirmation', type: 'boolean'}
            show:
                max_results: 20
            search:

            form:
                title: 'Ajout Prestataire'
                form_options: {validation_groups: ['Default']}
            new:
                form_options: {validation_groups:['Default','Prestataire']}
            edit:
              title: 'Modifier Prestataire'

        CategorieDeServices:
            class: AppBundle\Entity\CategorieDeServices
        Image:
            class: AppBundle\Entity\Image
            list:
                fields:
                    - id
                    - {property: 'nom', label: 'image', type: 'image', base_path: 'img/' }
                    - active
        Newsletter:
            class: AppBundle\Entity\Newsletter
            list:
                fields:
                    - id
                    - { property: 'titre', label: 'titre'}
                    - { property: 'publication', label: "Date de publication", type: 'datetime'}
                    - { property: 'documentPDF', label: 'pdf', type: 'file', base_path: 'pdf/'}

#        - AppBundle\Entity\Commentaire
#        - AppBundle\Entity\Promotion
#        - AppBundle\Entity\Stage
#        - AppBundle\Entity\Abus
#        - AppBundle\Entity\Bloc
#        - AppBundle\Entity\CodePostal
#        - AppBundle\Entity\Localite
#        - AppBundle\Entity\Image
#        - AppBundle\Entity\Newsletter

