# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        bien_etre:
            entity:
                class: AppBundle:Utilisateur
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            user_checker: AppBundle\Security\UserChecker
            anonymous: ~
            form_login:
                login_path: connexion
                check_path: connexion
                default_target_path: /
                always_use_default_target_path: true
            provider: bien_etre
            logout:
                path: /deconnexion
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        # require ROLE_USER for /profil*
        - { path: ^/profil, roles: ROLE_USER}

    encoders:
        AppBundle\Entity\Utilisateur:
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\UtilisateurTemporaire:
            algorithm: bcrypt
            cost: 12

